// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class CadastrandoveiculoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cadastrandoveiculo() {
    driver.get("http://localhost:8080/CRUD-SOCIALMOTORS/select.jsp");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.linkText("Novo Cadastro")).click();
    driver.findElement(By.name("ModeloVeiculo")).click();
    driver.findElement(By.name("ModeloVeiculo")).sendKeys("teste02");
    driver.findElement(By.name("MarcaVeiculo")).sendKeys("teste02");
    driver.findElement(By.name("Email")).sendKeys("teste@teste.com.br");
    driver.findElement(By.name("Data")).sendKeys("0002-11-19");
    driver.findElement(By.name("Data")).sendKeys("0020-11-19");
    driver.findElement(By.name("Data")).sendKeys("0201-11-19");
    driver.findElement(By.name("Data")).sendKeys("2019-11-19");
    driver.findElement(By.cssSelector(".btn-success")).click();
  }
}
